import pymongo 
import yaml

#setup mongoDB connection
my_client = pymongo.MongoClient("mongodb+srv://root:root@cluster0.56jzb.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db_name = my_client["Backend"]
collection_name = db_name["bbox_ref"]
count = collection_name.count_documents({})

#find the yaml file that was generated when bounding boxes were designed
file_name = input ("Enter yaml file name for the new module setup: ")

#parking lot name that the installation team is working at
parking_lot_name = input ("Enter the parkingLotName you are working at: ")

#query for the parking lot name in order to find the latest modID value
parking_lot_query = {"parkingLotName":parking_lot_name}
mydoc = collection_name.find(parking_lot_query)
for x in mydoc:
    #have the latest modID of the specific parking lot
    modID = x["modID"]

#open yml file generated by bounding box creation by installation team
ref_yaml_file = open("./yaml_files/" + file_name)
parsed_ref = yaml.load(ref_yaml_file, Loader=yaml.FullLoader)

for bbox in parsed_ref:
    coord = bbox["coordinates"]
    print(coord)

dict_insert = {"parkingLotName" : parking_lot_name,
               "modID" : modID + 1}

# How to insert a dict
#x = collection_name.insert_one(dict_insert)

#TODO: have to save the bounding box coordinates in the same way as used in computer vision

#TODO: count number of documents and set modID to count+1
